# Generated by Django 5.2.3 on 2025-06-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_student_email_student_level_user_profile_picture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="department",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="schedule",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="semester",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="units",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
