# Generated by Django 5.2.3 on 2025-06-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_course_department_course_description_course_schedule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="department",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
