# Generated by Django 4.2.23 on 2025-07-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_student_phone_user_last_name_user_bio_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="Last_name",
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                unique=True,
                verbose_name="username",
            ),
        ),
    ]
