# Generated by Django 4.2.23 on 2025-07-10 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_user_department_alter_user_faculty_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
