# Generated by Django 4.2.23 on 2025-07-14 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
