# Generated by Django 4.2.23 on 2025-07-24 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_user_is_active_alter_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="data_joined",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
