# Generated by Django 4.2.23 on 2025-07-27 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_user_data_joined"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_students",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
